config/routes.rb
Rails.application.routes.draw do
  resources :blogs do
    resources :comments, only: [:create, :edit, :update, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
    has_many :comments, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :blog
  validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[ show edit update destroy ]

  # GET /blogs or /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1 or /blogs/1.json
  def show
    @comments = @blog.comments
    @comment = @blog.comments.build
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs or /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to blog_url(@blog), notice: "Blog was successfully created." }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1 or /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to blog_url(@blog), notice: "Blog was successfully updated." }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1 or /blogs/1.json
  def destroy
    @blog.destroy

    respond_to do |format|
      format.html { redirect_to blogs_url, notice: "Blog was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:title, :description)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :set_blog

    def create
      @comment = @blog.comments.build(comment_params)
      respond_to do |format|
        if @comment.save
          flash.now[:notice] = 'コメントが投稿されました'
          format.js { render :index }
        else
          flash.now[:notice] = 'コメントの投稿に失敗しました'
          format.js { render :index }
        end
      end
    end
  
    def edit
        @comment = @blog.comments.find(params[:id])
        respond_to do |format|
          flash.now[:notice] = 'コメントの編集中'
          format.html { redirect_to @blog }
          format.js { render :edit }
        end
      end
    
      def update
        @comment = @blog.comments.find(params[:id])
        respond_to do |format|
          if @comment.update(comment_params)
            flash.now[:notice] = 'コメントが編集されました'
            format.js { render :index }
          else
            flash.now[:notice] = 'コメントの編集に失敗しました'
            format.js { render :index }
          end
        end
      end
      
      def destroy
        @comment = Comment.find(params[:id])
          @comment.destroy!
          respond_to do |format|
            flash.now[:notice] = 'コメントが削除されました'
            format.js { render :index }
          end
      end

    private
  
    def comment_params
      params.require(:comment).permit(:description, :blog_id)
    end
  
    def set_blog
      @blog = Blog.find(params[:blog_id])
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
        <% blog.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td><%= blog.description %></td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @blog.description %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

<hr>

<div id="comments_area">
  <%= render partial: 'comments/index', locals: { comments: @comments, blog: @blog } %>
</div>
<div id="form_area">
  <%= render partial: 'comments/form', locals: { comment: @comment, blog: @blog } %>
</div>

app/views/comments/_edit.html.erb
<%= render 'layouts/flash' %>
<div class="comment_edit_form">
  <%= form_with(model: [blog, comment]) do |form| %>
    <div class="field">
      <%= form.text_area :description, id: "comment_description_#{blog.id}" %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>

    <%= link_to :back do %>
      戻る
    <% end %>
  <% end %>
</div>

app/views/comments/_form.html.erb
<div class="comment-form">
  <%= form_with(model: [blog, comment]) do |form| %>
    <div class="field">
      <%= form.label :description, "コメント内容" %>
      <%= form.text_area :description %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/comments/_index.html.erb
<%= render 'layouts/flash' %>
<% comments.order(created_at: :asc).each do |comment| %>
    <div id ="this_comment_<%= comment.id %>">
        <%= simple_format(comment.description) %>
        <span>投稿日時:<%= time_ago_in_words(comment.created_at) %></span>
        <span><%= link_to 'Edit', edit_blog_comment_path(blog, comment), remote: true %></span>
        <span><%= link_to 'Destroy', blog_comment_path(comment.blog_id, comment.id), data: { confirm: "本当に削除しますか?"}, method: :delete, remote: true %></span>
    </div>
<% end %>

app/views/comments/edit.js.erb
$('.alert').remove();
$("#this_comment_<%= @comment.id %>").replaceWith("<%= j(render 'comments/edit', { blog: @blog, comment: @comment }) %>");

app/views/comments/index.js.erb
$("#comments_area").html("<%= j(render 'comments/index', { comments: @comment.blog.comments, blog: @comment.blog }) %>")
$("textarea").val('')

app/views/layouts/_flash.html.erb
<% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>">
      <%= message %>
    </div>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsAjaxCommentExample</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>